name: "Tests: Version"

on:
  workflow_call:
    inputs:
      php-version:
        required: false
        type: number
        default: 8.2
      terminus-version:
        required: false
        type: string
        default: 3.6.1

jobs:
  test_version:
    runs-on: ubuntu-latest
    name: ${{ inputs.terminus-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}

      - name: Setup Terminus
        uses: ./
        with:
          terminus-version: ${{ inputs.terminus-version }}

      - name: Expect to be version ${{ inputs.terminus-version }}
        run: |
          terminus -V --no-ansi
          if [[ $(terminus -V --no-ansi) != *"${{ inputs.terminus-version }}" ]]; then exit 1; fi
