name: Terminus Github Action Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test-with-login:
    runs-on: ubuntu-latest
    name: Test with Authentication
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terminus
        uses: ./
        with:
            pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN_CI }}
      - name: Terminus Command is available
        run: terminus -V
      - name: Who Am I?
        run: terminus auth:whoami
      - name: Expect terminus to print art
        run: terminus art
  test-using-cache:
    runs-on: ubuntu-latest
    name: Test Cache is Used
    needs: test-with-login
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Terminus
          uses: ./
          with:
            pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN_CI }}
        - name: Terminus Command is available
          run: terminus -V
        - name: Who Am I?
          run: terminus auth:whoami
        # TODO: Assert Cache used
        - name: Fail if Cache Not Recovered
          if: ${{ steps.test-with-login.outputs.session_found == 'false' }}
          run:  exit 1
  test-cache-not-used-when-disabled:
    runs-on: ubuntu-latest
    name: Test Cache is ignored when disabled
    needs: test-with-login
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Terminus
          uses: ./
          with:
            pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN_CI }}
            disable-cache: true
        - name: Terminus Command is available
          run: terminus -V
        - name: Who Am I?
          run: terminus auth:whoami
        - name: Fail if Cache Recovered and Used
          if: ${{ steps.test-with-login.outputs.session_found == 'true' }}
          run:  exit 1
  
  test_terminus_version:
    name: Terminus Version
    uses: ./.github/workflows/test-terminus-version.yml

  test_terminus_version_304:
    name: Terminus Version
    uses: ./.github/workflows/test-terminus-version.yml
    with:
      terminus-version: 3.0.4

  test_terminus_version_266:
    name: Terminus Version
    uses: ./.github/workflows/test-terminus-version.yml
    with:
      php-version: 7.4
      terminus-version: 2.6.6