name: Terminus Github Action Tests with Auth

on:
  pull_request:
    branches:
      - main

jobs:
  test-with-login:
    runs-on: ubuntu-latest
    name: Test with Authentication
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terminus
        uses: ./
        with:
            pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN_CI }}
      - name: Terminus Command is available
        run: terminus -V
      - name: Who Am I?
        run: terminus auth:whoami
  test-using-cache:
    runs-on: ubuntu-latest
    name: Test Cache is Used
    needs: test
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Terminus
          uses: ./
          with:
            pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN_CI }}
        - name: Terminus Command is available
          run: terminus -V
        - name: Who Am I?
          run: terminus auth:whoami
        # TODO: Assert Cache used
  test-cache-not-used-when-disabled:
    runs-on: ubuntu-latest
    name: Test Cache is ignored when disabled
    needs: test
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Terminus
          uses: ./
          with:
            pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN_CI }}
            disable-cache: true
        - name: Terminus Command is available
          run: terminus -V
        - name: Who Am I?
          run: terminus auth:whoami
        # TODO: Assert Cache not used