name: "Tests: Version"

on:
  workflow_call:
    inputs:
      php-version:
        required: false
        type: number
        default: 8
      terminus-version:
        required: false
        type: string
        default: 3.0.6

permissions:
  contents: read

jobs:
  test_version:
    runs-on: ubuntu-latest
    name: ${{ inputs.terminus-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ inputs.php-version }}

      - name: Setup Terminus
        uses: ./
        with:
          terminus-version: ${{ inputs.terminus-version }}

      - name: Expect to be version ${{ inputs.terminus-version }}
        run: |
          terminus -V --no-ansi
          if [[ $(terminus -V --no-ansi) != *"${{ inputs.terminus-version }}" ]]; then exit 1; fi
